# Generated by Django 4.1.1 on 2024-02-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hall_Admin', '0005_remove_hall_halladmin_remove_hall_provost'),
        ('Provost', '0001_initial'),
        ('Varsity_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallId', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('hallAdmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hall_Admin.halladmin')),
                ('provost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Provost.provost')),
            ],
        ),
    ]
