# Generated by Django 4.1.1 on 2024-02-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0002_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField(blank=True, default=0, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Varsity_Admin.hall')),
            ],
        ),
    ]
