# Generated by Django 4.1.1 on 2024-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
