# Generated by Django 4.1.1 on 2024-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_remove_student_hall_remove_student_room_and_more'),
        ('Staff', '0007_remove_visitor_hall_delete_staff_delete_visitor'),
        ('Varsity_Admin', '0004_room_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='hallAdmin',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='provost',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hall',
        ),
        migrations.DeleteModel(
            name='VarsityAdmin',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
