# Generated by Django 4.1.1 on 2024-02-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hall_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='hallAdmin',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='provost',
        ),
        migrations.AddField(
            model_name='halladmin',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hall_Admin.hall'),
        ),
    ]
