# Generated by Django 4.1.1 on 2024-02-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hall_Admin', '0002_remove_hall_halladmin_remove_hall_provost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halladmin',
            name='hall',
        ),
        migrations.AddField(
            model_name='hall',
            name='hallAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hall_Admin.halladmin'),
        ),
    ]
