# Generated by Django 4.1.1 on 2024-02-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Provost', '0001_initial'),
        ('Hall_Admin', '0003_remove_halladmin_hall_hall_halladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='provost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Provost.provost'),
        ),
    ]
