# Generated by Django 4.1.1 on 2024-02-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall_Admin', '0004_hall_provost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='hallAdmin',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='provost',
        ),
    ]
