# Generated by Django 4.1.1 on 2024-02-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall_Admin', '0005_remove_hall_halladmin_remove_hall_provost'),
        ('Staff', '0002_alter_staff_hall'),
        ('Student', '0006_alter_student_hall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
