# Generated by Django 4.1.1 on 2024-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0005_remove_hall_halladmin_remove_hall_provost_and_more'),
        ('Provost', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provost',
        ),
    ]
