# Generated by Django 4.1.1 on 2024-02-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provost', '0002_delete_provost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provostId', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(default='None', max_length=100)),
                ('password', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
