# Generated by Django 4.1.1 on 2024-02-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='departure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
