# Generated by Django 4.1.1 on 2024-02-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_visitor_arrival_alter_visitor_departure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='day',
            new_name='date',
        ),
    ]
