# Generated by Django 4.1.1 on 2024-02-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0004_room_color'),
        ('Staff', '0005_rename_day_visitor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Varsity_Admin.hall'),
        ),
    ]
