# Generated by Django 4.1.1 on 2024-02-16 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0006_initial'),
        ('Staff', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Varsity_Admin.hall'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 17)),
        ),
    ]
