# Generated by Django 4.2.10 on 2024-02-23 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Staff", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
    ]
