# Generated by Django 4.1.1 on 2024-02-20 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_alter_staff_hall_alter_visitor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
    ]
