# Generated by Django 4.2.10 on 2024-02-23 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Staff", "0009_alter_visitor_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
