# Generated by Django 4.2.10 on 2024-02-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Staff", "0010_alter_visitor_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="hall",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="hall",
        ),
    ]
