# Generated by Django 4.1.1 on 2024-02-24 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_alter_visitor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 24)),
        ),
    ]
