# Generated by Django 4.1.1 on 2024-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
