# Generated by Django 4.1.1 on 2024-02-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_swaprequest_repairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='noOfRequests',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
