# Generated by Django 4.1.1 on 2024-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_session_alter_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='csvFile',
            field=models.FileField(blank=True, null=True, upload_to='csvs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
