# Generated by Django 4.1.1 on 2024-02-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_session_csvfile_alter_student_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='residentId',
            new_name='studentId',
        ),
    ]
