# Generated by Django 4.1.1 on 2024-02-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Varsity_Admin', '0004_room_color'),
        ('Student', '0007_alter_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Varsity_Admin.room'),
        ),
    ]
