# Generated by Django 4.1.1 on 2024-02-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
