# Generated by Django 4.1.1 on 2024-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_student_studenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
