# Generated by Django 4.1.1 on 2024-02-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
